In [1]:
import pandas as pd
import numpy as np

In [2]:
d = np.random.randint([10, 25, 100], [50,35,150],size=(15,3))

In [3]:
d

array([[ 48,  30, 117],
       [ 39,  32, 115],
       [ 44,  28, 139],
       [ 28,  33, 120],
       [ 23,  29, 105],
       [ 17,  34, 110],
       [ 19,  30, 147],
       [ 20,  29, 119],
       [ 49,  31, 119],
       [ 45,  29, 146],
       [ 27,  33, 144],
       [ 33,  27, 102],
       [ 26,  31, 115],
       [ 11,  28, 123],
       [ 43,  28, 101]])

In [4]:
mu = np.mean(d,axis=0)

In [5]:
sigma = np.std(d,axis=0)

In [6]:
nd = (d-mu)/sigma

In [7]:
nd

array([[ 1.3772253 , -0.06468462, -0.29712993],
       [ 0.62752604,  0.90558472, -0.43017319],
       [ 1.04402563, -1.03495396,  1.16634586],
       [-0.28877305,  1.39071939, -0.09756505],
       [-0.70527263, -0.54981929, -1.09538946],
       [-1.20507214,  1.87585406, -0.76278132],
       [-1.0384723 , -0.06468462,  1.69851888],
       [-0.95517238, -0.54981929, -0.16408668],
       [ 1.46052522,  0.42045005, -0.16408668],
       [ 1.12732555, -0.54981929,  1.63199725],
       [-0.37207296,  1.39071939,  1.49895399],
       [ 0.12772654, -1.52008863, -1.29495434],
       [-0.45537288,  0.42045005, -0.43017319],
       [-1.70487164, -1.03495396,  0.10199983],
       [ 0.96072571, -1.03495396, -1.36147597]])

In [8]:
cov_matrix = np.cov(nd,rowvar=False)

In [9]:
cov_matrix

array([[ 1.07142857, -0.17300047,  0.0173098 ],
       [-0.17300047,  1.07142857,  0.11771577],
       [ 0.0173098 ,  0.11771577,  1.07142857]])

In [10]:
mu1 = np.mean(nd,axis=0)

In [11]:
cov_matrix_m = (np.dot((nd-mu1).T,(nd-mu1)))/15

In [12]:
val,vect = np.linalg.eig(cov_matrix)

In [13]:
val1,vect1 = np.linalg.eig(cov_matrix_m)

In [14]:
vect

array([[ 0.58471899,  0.58662215,  0.56033755],
       [ 0.69309933, -0.7201875 ,  0.03071292],
       [-0.42156497, -0.37041115,  0.82769472]])

In [15]:
val

array([0.85388182, 1.2728888 , 1.08751509])

In [16]:
w=vect[1:]

In [17]:
w

array([[ 0.69309933, -0.7201875 ,  0.03071292],
       [-0.42156497, -0.37041115,  0.82769472]])

In [18]:
reduced_matrix = np.transpose(np.dot(w,nd.T))